### ISSUE TITLE
Add general XDR page (should we?)

### ISSUE THREAD

**Issue by irisli** [stellar/docs#107]
One already exists for https://www.stellar.org/developers/horizon/learn/xdr.html but perhaps we can consider making a page for just XDR.

**Comment by irisli** [comment]
This would be useful to link to from the laboratory since the laboratory often talks about XDR.

**Comment by Mr0grog** [comment]
Is there a reason not to just *move* that page from the Horizon docs to `/learn/concepts/xdr.md` here?

Should we also add a bit about *why* XDR instead of a human-readable text format used elsewhere in Stellar like JSON, YAML, TOML?
  - More compact
  - Reliable/predictable serializing so the same set of data will always result in the same string for signing
  - Implicitly makes assertions about valid structures/content
  - Can be more precise about data types
  - What else?

What else would/should change about that doc?
