### ISSUE TITLE
Docs should warn that setting thresholds and signer weights must be done Very Carefully

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/docs#486]
The [`Set Options`](https://www.stellar.org/developers/guides/concepts/list-of-operations.html#set-options) operation is an unassuming-looking operation that is actually extremely powerful. The ramifications are not obvious to the uninformed user. A user can easily render their account inoperable with a single call to `Set Options`.

For example, assume you have only one authorised signer. Then:
- if you set your master key weight to 0, it's game over - you can't do anything any more. Everything is now read-only.
- if you change the "high" threshold to a number larger than your master key weight, you lose all ability to change options in the future. In particular this means you can't add or remove new signers or adjust thresholds for the account. Effectively you've frozen the account's access permissions.
- if you also change the "medium" threshold to exceed the master key weight it's even worse - now you can't transfer funds out of your account at all ([Payment](https://www.stellar.org/developers/guides/concepts/list-of-operations.html#payment) is a medium threshold operation)!

Beyond the fact that this is completely trivial to do (just one number in an SDK call!), one way that this could happen inadvertently is while setting up additional signers. If you set the threshold(s) before adding the new signer (with correct weight), then these scenarios apply. Even if you do them together, if you make a mistake with "high" threshold, then you can't undo that.

For these reasons there should be clear warnings in the docs that these operations are **Danger Zone/Think Very Carefully Because These May Be Irreversible** actions.

Additionally, from a protocol/SDK view it's not practical to sanity check these, but it should probably be a best practice for clients to either not expose these options, or do basic checks e.g. to determine unreachable permissions after executing these operations, and confirm these explicitly with the user. That might make sense in a SEP, a best practice guide or elsewhere.

**Comment by leighmcculloch** [comment]
I just experienced this issue that @ire-and-curses describes where setting the low threshold in this example: https://repl.it/repls/UsableBurlyDesigns

It makes sense that a fee requires low-threshold since money is leaving the account, and the docs at the link below even explicitly mention that, but it's quite difficult to imagine all the constraints in these unique situations without first making the mistake.

Could we add to the multi-sig page a list of gotcha scenarios and what constraints will show up in each?

https://www.stellar.org/developers/guides/concepts/multi-sig.html

cc @rice2000

**Comment by rice2000** [comment]
This was resolved recently in the new docs: we added warnings and removed dicey examples.
