### ISSUE TITLE
Add opcodes in list of operations

### ISSUE THREAD

**Issue by msfeldstein** [stellar/docs#507]
It is difficult to find info on what horizon errors mean.

When a horizon call fails, it returns an opcode (`tx_bad_auth` for example) and sends you to our docs for more info.  It says `Descriptions of each code can be found at: https://www.stellar.org/developers/learn/concepts/list-of-operations.html"` however when you get to that page if you try to search for your opcode nothing comes up.  We should have the actual opcodes next to the horizon error codes.

tx_bad_auth probably is ALLOW_TRUST_TRUST_NOT_REQUIRED but i'm not really sure.  It would be great to know for sure.

```
{
  "type": "https://stellar.org/horizon-errors/transaction_failed",
  "title": "Transaction Failed",
  "status": 400,
  "detail": "The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://www.stellar.org/developers/learn/concepts/list-of-operations.html",
  "extras": {
    "envelope_xdr": "AAAAAFwDjFmQjkmPnH19otvP2uTV4jysFElqpOliy0QMET2RAAAAZAGECIwAAAADAAAAAQAAAAAAAAAAAAAAAF1wBy0AAAAAAAAAAQAAAAAAAAAGAAAAAVVTRFgAAAAAwgJ23a31Zxez/bwxmU6+6LOrn5BEE1gH0tUg2sanCd9//////////wAAAAAAAAABDBE9kQAAAEB8Ui9EHTSzkhpakuTuD6jYBI1UPUEN6+o4EY5muNhv0/xl7g7MTIj9mwKTelv7Wt653fiR/vjtuDRKVpR3YTAL",
    "result_codes": {
      "transaction": "tx_bad_auth"
    },
    "result_xdr": "AAAAAAAAAGT////6AAAAAA=="
  }
}
```

**Comment by msfeldstein** [comment]
Looks similar to #179 which was closed but I don't think it was solved

**Comment by bartekn** [comment]
For reference the codes can be found in [`codes`](https://github.com/stellar/go/blob/686ff67c65e9d8a90bd993f8b21c871efc06f9cc/services/horizon/internal/codes/main.go) package. I think that primary reason for this was to merge similar error codes into one, ex. all different operation success codes are now `op_success`. But you are right we should either update the docs or display original errors returned by stellar-core in Horizon response.

**Comment by ire-and-curses** [comment]
I don't really see the value in merging the similar codes into a smaller number of generic codes. Whether generic or not the caller probably needs to track the context of what was sent, to choose an appropriate specific follow-up action to the error (e.g. retry vs abort). Also the original stellar core errors reflect the underlying XDR, and I think abstracting this here doesn't aid comprehension.

`tx_bad_auth` is slightly different though. This is an error at the transaction level, because Horizon validated your TX and concluded it would never work (due to bad/missing signature and/or bad network passphase). Documentation for this (and other Horizon validation checks) should be clearly linked in the returned error. We do have a decent doc page [here](https://www.stellar.org/developers/horizon/reference/errors/transaction-failed.html) so I think the issue is making sure we link to it.

So:
1) We should fix the docs to link to the Horizon errors (probably at the top of list of operations)
2) Overall I think I'm in favour of changing the codes to be explicit. This would be a pretty major breaking change. @tomq @tomerweller @rice2000 what are your thoughts?

**Comment by msfeldstein** [comment]
Agree with eric, and as a tiny point i'd mention on that page that bad auth
is often caused by signing for the right network

**Comment by tomerweller** [comment]
I agree with @ire-and-curses. The return codes are well defined and documented in the [transactions xdr definitions](https://github.com/stellar/stellar-core/blob/master/src/xdr/Stellar-transaction.x) ([txBAD_AUTH example](https://github.com/stellar/stellar-core/blob/master/src/xdr/Stellar-transaction.x#L804)). Abstracting over these is causing us unnecessary pain.

We can import these error comments to the horizon documentation and even use them to generate human readable error messages in the response from a failed transaction submission.

**Comment by rice2000** [comment]
It looks like this situation has been improved by the `API Reference` section of the new docs here: https://developers.stellar.org/api/errors/result-codes/

Is that sufficient to solve this issue?

**Comment by ire-and-curses** [comment]
As you point out @rice2000, the new docs have the Horizon errors and the mapping to XDR opcodes. I think this is sufficient for the docs issue. I'll open an issue on Horizon to discuss whether to make the breaking change to move to explicit opcodes in a future version of the API.
