### ISSUE TITLE
Feature Request: more detailed documentation for `limit` argument

### ISSUE THREAD

**Issue by staktrace** [stellar/docs#560]
### What problem does your feature solve?
I was looking at the "Payments for Account" operation documentation [here](https://www.stellar.org/developers/horizon/reference/endpoints/payments-for-account.html) and trying to figure out how to make the `limit` argument indicate "unlimited". The default is "10" which is quite low, and the documentation doesn't say that passing "0" or some such value would treat the limit as unlimited. If that's the case it should be documented. Failing that, I would pass in some large value, but it's not clear how large of a value I can pass. Is `limit` a u32? Or a u64?

### What would you like to see?
Documentation that indicates the canonical method of getting either "unlimited" or "practically unlimited" payment operations.

### What alternatives are there?
I guess I can just put in u32 max value for now and hope for the best.

**Comment by ire-and-curses** [comment]
The limit argument can't be made unlimited, because that wouldn't make sense. All endpoints must be responsive and return promptly, so data for a single call must be limited.

At the moment, the limit is 200, but this is not a contract and that number could change. You should use `the next` link to traverse consecutive calls.

Alternatively, you can use the streaming interface to listen to all payments.

Closing this because `next` and the streaming interface are both documented, and the max limit is not something to rely on.

**Comment by staktrace** [comment]
I was actually trying to use this API in streaming mode, but it would be closed by the server after a few seconds. I thought (wrongly) that I could pass in a bigger limit to keep it open longer, but that turned out not to be the case. Instead I just have to keep reconnecting to the server, which seems kinda inefficient but is not the end of the world.
